wowloot/urls.py
from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^treasure/', include(admin.site.urls)),
    url(r'^', include('calcloot.urls')),
]

calcloot/forms.py
from django import forms
from calcloot.models import *
from calcloot.fields import ListTextWidget

class HomeForm(forms.ModelForm):
    class Meta:
        model = Calculation
        fields = ('name',)

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        exclude = ('calculation', 'benefactors',)
        widgets = {
            'amount': forms.TextInput(attrs={'size': '8'}),
            'name': forms.TextInput(attrs={'size': '25'}),
            }

class AddPersonForm(forms.Form):
    name = forms.CharField(max_length = 200)

    def __init__(self, *args, **kwargs):
        name_list = kwargs.pop('data_list', None)
        super(AddPersonForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget = ListTextWidget(data_list=name_list, name='name-list')

class ShareForm(forms.Form):
    address = forms.EmailField(widget = forms.TextInput(attrs={'size': '50'}))

class ChangeCurrencyForm(forms.ModelForm):
    class Meta:
        model = Calculation
        fields = ('currency',)

templates/about.html
{% extends 'base.html' %}

{% block title %} - About{% endblock %}

{% block toplinks %}home{% endblock %}

{% block contentwrapperstart %}
<div class="firstpagemaincontent">
  {% endblock %}
  {% block content %}
  <div class="firstpagetext">
    Who Ows What Loot is a small web application for calculating who needs to pay what to whom, for example after a trip.
  </div>
  <div class="firstpagetext">
    It is created by Malte Lenz (<a href="http://maltelenz.com/" class="aboutlink">maltelenz.com</a>). The source code is available on <a href="https://github.com/maltelenz/wowloot/" class="aboutlink">github</a> for any non-commercial use. 
  </div>
  {% endblock %}
  {% block contentwrapperend %}
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    
    <title>Who Ows What loot {% block title %}{% endblock %}</title>
    
    <!-- CSS -->
    <link rel="stylesheet" href="{{ STATIC_URL}}style.css" />
    <script src="{{ STATIC_URL }}jquery-1.12.0.min.js"></script>
    <link rel="shortcut icon" href="http://wowloot.se/favicon.ico" />
    {% block inheader %}{% endblock %}
  </head>
  <body>
    <div class="toplinks toplinks{% block toplinks %}{% endblock %}">
      <a href="{% url 'home' %}">Home</a>
      <a href="{% url 'about' %}">About</a>
    </div>
    {% block contentwrapperstart %}{% endblock %}
    <h1 class="firstpage"><a href="{% url 'home' %}"><img src="{{ STATIC_URL }}images/logo.png" alt="icon" class="logo"/>WhoOwsWhat Loot</a></h1>
    <hr class="header"/>

    {% block content %}{% endblock %}
    {% block contentwrapperend %}{% endblock %}
  </body>
</html>

templates/calculation.html
{% extends 'base.html' %}

{% block title %} - {{ calculation.name }}{% endblock %}

{% block inheader %}
<script>
  $(document).ready(function() {
    $("a[explanationLink]").click(function() {
      $(this).toggleClass('withBubble');
      return false;
    }).hover(function() {
      $(this).addClass("withBubble");
    }, function() {
      $(this).removeClass("withBubble");
    });
  });
</script>
{% endblock%}

{% block toplinks %}calculation{% endblock %}

{% block contentwrapperstart %}
<div class="calculationmaincontent">
  {% endblock %}

  {% block content %}
  <div class="floatingsharebutton">
    <a href="{% url 'calculation_share' calculation.id calculation.hashtag %}">
      <img src="{{ STATIC_URL }}images/s.png" alt="Share"/> Share
    </a>
  </div>
  <h2 class="calculation">{{ calculation.name }}</h2>
  <h3>Currency</h3>
  <form action="{% url 'change_currency' calculation.id calculation.hashtag %}" method="post" {% if firstload %}class="withBubble" explanationLink="Start by choosing the currency you will pay back in."{% endif %}>
    {% csrf_token %}
    {{ currencyform.currency }}
    <input type="submit" value="Change">
  </form>
  <h3>Expenses</h3>
  <table class="expensetable">
    <tr class="header">
      <td class="header iconcolumn">&nbsp;</td>
      <td class="header">Who paid?</td>
      <td class="header">Amount <span class="balancecurrency">[{{calculation.currency.name}}]</span></td>
      <td class="header">For what? (optional)</td>
      {% for person in calculation.involved.all %}
        <td class="header{% if person.finished %} tabledone{% endif %}">
          {% if person.finished %}
          <a href="{% url 'unfinish_person' calculation.id calculation.hashtag person.id %}" title="Mark not finished">
          {% else %}
          <a href="{% url 'finish_person' calculation.id calculation.hashtag person.id %}" title="Mark finished">
          {% endif %}
            {{ person.name }}
          </a>
          <a href="{% url 'delete_person' calculation.id calculation.hashtag person.id %}"><img src="{{STATIC_URL}}images/cross.png" alt="D" title="Remove" /></a>
      </td>
      {% endfor %}
      <td class="headernew{% if not firstload and not calculation.involved.all %} withBubble{% endif %}" explanationLink="Now add everyone involved in the calculation.">
        <form action="{% url 'add_person' calculation.id calculation.hashtag %}" method="post">
          {% csrf_token %}
          {{ addpersonform.name }}
          <input type="submit" value="Add person">
        </form>
      </td>
    </tr>
    {% for expense in ordered_expenses %}
    {% if forloop.counter|divisibleby:10 %}

    <tr class="subheader">
      <td class="subheader iconcolumn">&nbsp;</td>
      <td class="subheader">Who paid?</td>
      <td class="subheader">Amount <span class="balancecurrency">[{{calculation.currency.name}}]</span></td>
      <td class="subheader">Name</td>
      {% for person in calculation.involved.all %}
      <td class="subheader">
        {{ person.name }}
      </td>
      {% endfor %}
    </tr>
    {% endif %}

    <tr class="{% cycle 'even' 'odd' %}">
      <td class="iconcolumn">
        <a href="{% url 'expense_delete' calculation.id calculation.hashtag expense.id %}"><img src="{{STATIC_URL}}images/cross.png" alt="D" /></a>
        <a href="{% url 'expense_edit' calculation.id calculation.hashtag expense.id %}"><img src="{{STATIC_URL}}images/pencil.png" alt="E" /></a>
      </td>
      <td>{{ expense.person.name }}</td>
      <td>{{ expense.amount_in_calculation_currency|floatformat:2 }}
        {% if expense.currency != calculation.currency %}({{ expense.amount }} {{ expense.currency.name }})
        {% endif %}
      </td>
      <td>{{ expense.name }}</td>
      {% for person in calculation.involved.all %}
      <td{% if person.finished %} class="tabledone"{% endif %}>{% if person in expense.benefactors.all %}
        <a href="{% url 'benefactor_delete' calculation.id calculation.hashtag expense.id person.id %}">
        <img src="{{STATIC_URL}}images/tick.png" alt="x" />
        </a>
        {% else %}
        <a href="{% url 'benefactor_add' calculation.id calculation.hashtag expense.id person.id %}">
          -
        </a>
        {% endif %}
      </td>
      {% endfor %}
    </tr>
    {% endfor %}
    {% if calculation.involved.count != 0 %}
    <form action="{{ request.get_full_path }}" method="post">
      {% csrf_token %}
      <tr class="tablenew">
        <td class="iconcolumn">
          <img src="{{STATIC_URL}}images/{% if is_edit %}editgrey{% else %}addgrey{% endif %}.png" />
        </td>
        <td>
          {% if not ordered_expenses and calculation.involved.all|length > 1 %}<span id="expenses" class="withBubble" explanationLink="Add your expenses here."></span>{% endif %}
          {{ form.person }}
        </td>
        <td>
          {{ form.amount }}
          {{ form.currency }}
        </td>
        <td>
          {{ form.name }}
        </td>
        {% for person in calculation.involved.all %}
        <td>
          {% if forloop.last %}
          <input type="submit" value="Add expense">
          {% endif %}
        </td>
        {% endfor %}
      </tr>
    </form>
    {% endif %}
    <tr class="balance">
      <td colspan="4">Balance <span class="balancecurrency">[{{calculation.currency.name}}]</span></td>
      {% for person in calculation.involved.all %}
      <td>
        {% for key, value in owing.items %}
        {% if key == person %}{{ value|floatformat:2 }}{% endif %}
        {% endfor %}
      </td>
      {% endfor %}
    </tr>
  </table>
  <h3>Solution ({% if calculation.is_finished %}Finished{% else %}Not finished<a href="#" explanationLink="Mark when you are finished by clicking your name at the top of the list of expenses.">?</a>{% endif %})</h3>
  {% for from_person, to_person, amount in transfers %}
  <div class="solutionrow{% if not calculation.is_finished %} solutionunfinished{% endif %}"><span class="personname">{{ from_person }}</span> pays <span class="personname">{{ to_person }}</span> {{ amount|floatformat:2 }} {{ calculation.currency.name }}</div>
  {% endfor %}

  {% endblock %}
  
  {% block contentwrapperend %}
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block inheader %}
<script>
  $(document).ready(function() {
  
  // Define what happens when the textbox comes under focus
  // Remove the watermark class and clear the box
  $("#id_name").focus(function() {
  
  $(this).filter(function() {
  
  // We only want this to apply if there's not 
  // something actually entered
  return $(this).val() == "" || $(this).val() == "Name..."
  
  }).removeClass("watermarked").val("");
  
  });
  
  // Define what happens when the textbox loses focus
  // Add the watermark class and default text
  $("#id_name").blur(function() {
  
  $(this).filter(function() {
  
  // We only want this to apply if there's not
  // something actually entered
  return $(this).val() == ""
  
  }).addClass("watermarked").val("Name...");
  
  });
  
  });
</script>
{% endblock %}

{% block toplinks %}home{% endblock %}

{% block contentwrapperstart %}
<div class="firstpagemaincontent">
  {% endblock %}
  {% block content %}
  {% if error_message %}<div>{{ error_message }}</div>{% endif %}
  <div class="firstpagetext">
    Find the easiest way to even out expenses paid, for example after a trip.
  </div>
  <div class="firstpagetext">
    Start by choosing a name for the calculation:
  </div>
  <div class="firstpageform">
    <form action="{% url 'home' %}" method="post">
      {% csrf_token %}
      {% if form.non_field_errors %}
      <div class="formerrors">{{ form.non_field_errors }}</div>
      {% endif %}
      {% if form.name.errors %}
      <div class="formerrors">{{ form.name.errors }}</div>
      {% endif %}
      <div>
        <input id="id_name" type="text" name="name" maxlength="200" class="inputfirstpage watermarked" value="Name...">
        <input type="submit" value="Start" class="firstpagesubmit"/>
      </div>
    </form>
  </div>
  {% if previous_calculations %}
  <h3>
    Previous calculations:
  </h3>
  <table class="previouscalculations">
    {% for calculation in previous_calculations %}
    <tr>
      <td>
        <a href="{% url 'calculation' calculation.id calculation.hashtag %}">{{ calculation.name }}</a>
      </td>
      <td class="creationdate">
        (Created {{ calculation.creation_date }})
      </td>
      <td>
        <a href="{% url 'calculation_delete' calculation.id calculation.hashtag %}"><img src="{{STATIC_URL}}images/cross.png" alt="Delete" /></a>
      </td>
    </tr>
    {% endfor %}
  </table>
  {% endif %}
  {% endblock %}
  {% block contentwrapperend %}
</div>
{% endblock %}

templates/share.html
{% extends 'base.html' %}

{% block title %} - Share{% endblock %}

{% block toplinks %}home{% endblock %}

{% block contentwrapperstart %}
<div class="firstpagemaincontent">
  {% endblock %}
  {% block content %}
  <h2 class="calculation">{{ calculation.name }}</h2>
  <div class="stext">
    <img src="{{ STATIC_URL }}images/link.png" alt="link"/> Share the calculation by giving someone this link:
    <input type="text" value="{{full_uri}}" readonly="readonly" class="copyurlfield"/>
  </div>
  <div class="stext">
    <img src="{{ STATIC_URL }}images/email.png" alt="email"/> Share the calculation via email:
    <textarea readonly="readonly" class="copyurlfield">{{ email_text }}</textarea>
    <form action="{% url 'calculation_share' calculation.id calculation.hashtag %}" method="post" style="padding-top: 5px;">
      {% csrf_token %}
      {{ form.address }}
      <input type="submit" value="Send email">
    </form>
  </div>
  <div class="backtocalc">
    &laquo; <a href="{% url 'calculation' calculation.id calculation.hashtag %}">Back to calculation</a>
  </div>
  {% endblock %}
  {% block contentwrapperend %}
</div>
{% endblock %}